name: la_red
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  provider: ^4.3.2+3
  path_provider: ^1.6.24
  fab_circular_menu: ^1.0.1
  card_settings: ^1.16.2
  font_awesome_flutter: ^8.11.0

dependency_overrides:
cupertino_icons: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  ios: true
  android: true
  image_path: "assets/images/componente.jpeg"

  build_runner: ^1.10.11
  hive_generator: ^0.8.2

flutter:

  uses-material-design: true


  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
